name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        mkdir -p appdir/usr/share/{applications,icons/hicolor/32x32/apps}
        cp NDS_Banner_Editor.desktop appdir/usr/share/applications
        cp icon.png appdir/usr/share/icons/hicolor/32x32/apps/NDS_Banner_Editor.png

        mkdir -p resources/i18n
        lrelease NDS_Banner_Editor.pro && mv i18n/*.qm resources/i18n
        qmake -config release
        make -j$(nproc)
        make INSTALL_ROOT=appdir -j$(nproc) install

        curl -o linuxdeployqt -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod a+x linuxdeployqt

        ./linuxdeployqt appdir/usr/share/applications/NDS_Banner_Editor.desktop -appimage
        mv NDS_Banner_Editor-*-x86_64.AppImage NDS_Banner_Editor.AppImage
        tar -cf NDS_Banner_Editor_Linux_x64.tar NDS_Banner_Editor.AppImage
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: NDS_Banner_Editor_Linux_x64.tar
        name: linux_x64
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: NDS_Banner_Editor_Linux_x64.tar
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: make
      run: |
        mkdir -p resources/i18n
        lrelease NDS_Banner_Editor.pro && mv i18n/*.qm resources/i18n
        qmake -config release
        make -j$(sysctl -n hw.ncpu)
        macdeployqt NDS_Banner_Editor.app -dmg
        mv NDS_Banner_Editor.dmg NDS_Banner_Editor_mac_x64.dmg
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: NDS_Banner_Editor_Mac_x64.dmg
        name: macos_x64
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: NDS_Banner_Editor_Mac_x64.dmg
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msys2-arch: x86_64
            mingw-arch: mingw64
            package-arch: x64
          - msys2-arch: i686
            mingw-arch: mingw32
            package-arch: x86
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw-arch }}
        update: true
    - name: Install Qt
      run: pacman -S --noconfirm mingw-w64-${{ matrix.msys2-arch }}-{gcc,make,qt5-static}
    - name: make
      run: |
        mkdir -p resources/i18n
        /${{ matrix.mingw-arch }}/qt5-static/bin/lrelease NDS_Banner_Editor.pro && mv i18n/*.qm resources/i18n
        /${{ matrix.mingw-arch }}/qt5-static/bin/qmake.exe -config release -config static
        mingw32-make.exe
        cd release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: release/NDS_Banner_Editor.exe
        name: windows_${{ matrix.package-arch }}
    - name: Zip binary
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      shell: powershell
      run: Compress-Archive -Path 'release\NDS_Banner_Editor.exe' -DestinationPath 'NDS_Banner_Editor_Win_$${{ matrix.package-arch }}.zip'
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
      with:
        files: NDS_Banner_Editor_Win_${{ matrix.package-arch }}.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}

